version: "3"
services:
  app:
    build:
      context: ./tools/docker/runtimes/7.4prod
      args:
        WWWGROUP: '${WWWGROUP}'
    container_name: kairos

    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: 1234

    volumes:
      - ./tools/docker/bash_aliases:/home/developer/.bash_aliases
      - .:/var/www

    ports:
      - 8000:80

networks:
  default:
      name: nginx-proxy