###=========================
@baseUrl = http://syndication.vm/api/admin

###=========================

# @name auth
POST {{baseUrl}}/operators/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin1@admin.com",
    "password": "secret"
}

### ==================================

# # @name logout
# POST {{baseUrl}}/operators/logout HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer {{auth.response.body.token}}

# ### ==================================

# # @name logout
# POST {{baseUrl}}/operators/me HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer {{auth.response.body.token}}

# ### ==================================
