###=========================
@baseUrl = http://syndication.vm/api/admin

###=========================

# @name auth
POST {{baseUrl}}/operators/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin1@admin.com",
    "password": "secret"
}

###=========================

# @name create
POST {{baseUrl}}/operators/admin/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
    "name": "test v999",
    "email": "admin-v999@default.com"
}

###=========================

# @name reset-my-password

POST {{baseUrl}}/operators/reset-my-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{auth.response.body.token}}

{
    "id": 2,
    "currentPassword": "secret",
    "newPassword": "secret-v2"
}
